#!/usr/bin/env bash

echo "Copying screenrc to home directory..."
cp ./user_config/.screenrc $HOME/
if [ $? -eq 0 ]; then
  echo ".screenrc copied successfully!"
else
  echo "Failed to copy .screenrc to home directory, try yourself!"
fi

echo "Copying user scripts to /usr/local/bin"
sudo cp ./user_bin/* /usr/local/bin/
if [ $? -eq 0 ]; then
  echo "User scripts copied successfully!"
else
  echo "Failed to copy user scripts to /usr/local/bin, try yourself!"
fi

echo "Reinstalling poweroff service"
./poweroff/uninstall
cd poweroff
sudo ./install
if [ $? -eq 0 ]; then
  echo "Poweroff service installed successfully!"
else
  echo "Failed to install poweroff service, try yourself!"
fi

echo "Setting up keyboard"
cd keyboard
sudo ./setup_keyboard.sh
if [ $? -eq 0 ]; then
  echo "Keyboard setup script ran successfully!"
else
  echo "Failed to run keyboard setup script, try yourself!"
fi

