#!/usr/bin/env bash

echo "Uninstalling picopoweroff service and related files..."
# Stop and disable the service
sudo systemctl stop picopoweroff.service
if [ $? -ne 0 ]; then
  echo "Failed to stop picopoweroff.service, it may not be running."
fi
sudo systemctl disable picopoweroff.service
if [ $? -ne 0 ]; then
  echo "Failed to disable picopoweroff.service, it may not be enabled."
fi

# Remove the service file
sudo rm -f /usr/lib/systemd/system/picopoweroff.service
if [ $? -ne 0 ]; then
  echo "Failed to remove picopoweroff.service file, it may not exist."
fi

echo "Reloading systemd daemon..."
sudo systemctl daemon-reload
if [ $? -ne 0 ]; then
  echo "Failed to reload systemd daemon, try yourself!"
fi

echo "Uninstallation complete!"